// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const CreateLazyImport = createFileRoute('/create')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const WPrivateKeyLazyImport = createFileRoute('/w/$privateKey')()
const WPrivateKeyDepositLazyImport = createFileRoute('/w/$privateKey/deposit')()

// Create/Update Routes

const CreateLazyRoute = CreateLazyImport.update({
  path: '/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/create.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const WPrivateKeyLazyRoute = WPrivateKeyLazyImport.update({
  path: '/w/$privateKey',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/w.$privateKey.lazy').then((d) => d.Route))

const WPrivateKeyDepositLazyRoute = WPrivateKeyDepositLazyImport.update({
  path: '/w/$privateKey/deposit',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/w_.$privateKey.deposit.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      preLoaderRoute: typeof CreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/w/$privateKey': {
      preLoaderRoute: typeof WPrivateKeyLazyImport
      parentRoute: typeof rootRoute
    }
    '/w/$privateKey/deposit': {
      preLoaderRoute: typeof WPrivateKeyDepositLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  CreateLazyRoute,
  WPrivateKeyLazyRoute,
  WPrivateKeyDepositLazyRoute,
])
